package io.github.toolicious.labler.render

import java.util.Base64
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotNull
import org.junit.Assert.assertNull
import org.junit.Assert.assertTrue
import org.junit.Test

/**
 * Holds the rMQR encoder against symbols produced by a second implementation.
 *
 * A barcode that looks plausible but does not follow the standard is worse than none, because the
 * mistake only shows up at the scanner. `resources/rmqr/fixtures.txt` therefore carries symbols
 * generated by the Python library `OUDON/rmqrcode-python`, and the encoder has to reproduce them
 * module for module. `generate.py.txt` beside them is the script that made them.
 *
 * That reference has three faults, all confirmed against Zint and against its own other fields, and
 * the script repairs them before generating: R13x27 carries 12 data codewords rather than 14,
 * R17x43 puts 61 rather than 60 codewords into its block, and its interleaver drops one codeword on
 * the eight versions whose blocks are of unequal length. The remaining agreement is what this test
 * checks, and it covers the parts most easily got wrong: bit order, the zigzag, the mask, and the
 * format information with its two different XOR patterns.
 */
class RmqrEncoderTest {

    private class Case(val version: String, val mode: String, val text: String, val rows: List<String>)

    private fun fixtures(): List<Case> {
        val stream = checkNotNull(javaClass.getResourceAsStream("/rmqr/fixtures.txt")) {
            "fixtures.txt is missing from the test resources"
        }
        val lines = stream.bufferedReader().readLines()
        val cases = mutableListOf<Case>()
        var i = 0
        while (i < lines.size) {
            val line = lines[i]
            if (line.isBlank()) { i++; continue }
            require(line.startsWith("CASE ")) { "unexpected line: $line" }
            val (_, version, mode, encoded) = line.split(" ")
            val height = version.substringAfter('R').substringBefore('x').toInt()
            cases += Case(
                version = version,
                mode = mode,
                text = String(Base64.getDecoder().decode(encoded), Charsets.UTF_8),
                rows = lines.subList(i + 1, i + 1 + height).toList(),
            )
            i += height + 1
        }
        return cases
    }

    private fun versionNamed(name: String) = RMQR_VERSIONS.first { it.name == name }

    private fun Array<BooleanArray>.render() = map { row -> row.joinToString("") { if (it) "#" else "." } }

    @Test
    fun `every reference symbol is reproduced module for module`() {
        val cases = fixtures()
        assertTrue("expected a good number of fixtures, got ${cases.size}", cases.size >= 50)
        for (case in cases) {
            val symbol = RmqrEncoder.encode(case.text, versionNamed(case.version))
            assertNotNull("${case.version}/${case.mode}: nothing encoded", symbol)
            assertEquals(
                "${case.version}/${case.mode} with ${case.text.length} characters",
                case.rows,
                symbol!!.modules.render(),
            )
        }
    }

    @Test
    fun `the fixtures cover every version`() {
        assertEquals(
            RMQR_VERSIONS.map { it.name }.toSet(),
            fixtures().map { it.version }.toSet(),
        )
    }

    @Test
    fun `the version table is internally consistent`() {
        assertEquals(32, RMQR_VERSIONS.size)
        RMQR_VERSIONS.forEachIndexed { index, v ->
            assertEquals("version indicator of ${v.name}", index, v.index)
            assertTrue("${v.name} has more data than it holds", v.dataCodewords < v.totalCodewords)
            assertEquals(
                "${v.name} splits its parity unevenly over its blocks",
                0,
                (v.totalCodewords - v.dataCodewords) % v.blocks,
            )
        }
    }

    @Test
    fun `text beyond the capacity does not encode`() {
        val smallest = versionNamed("R7x43")
        // Six data codewords, so a handful of characters at most.
        assertNotNull(RmqrEncoder.encode("12345", smallest))
        assertNull(RmqrEncoder.encode("x".repeat(200), smallest))
        assertNull(RmqrEncoder.encode("", smallest))
    }

    @Test
    fun `a wide flat box gets a wide flat symbol with the largest modules that fit`() {
        // The shape of a code on 12 mm tape: room along the tape, almost none across it.
        val symbol = checkNotNull(RmqrEncoder.fit("LABEL 42", boxWidth = 400, boxHeight = 40))
        assertTrue("expected a flat symbol, got ${symbol.version.name}", symbol.height <= 11)

        val scale = minOf(
            400 / (symbol.width + 2 * RmqrEncoder.QUIET_ZONE),
            40 / (symbol.height + 2 * RmqrEncoder.QUIET_ZONE),
        )
        // No other version that holds the text may offer larger modules.
        val better = RMQR_VERSIONS.filter { RmqrEncoder.encode("LABEL 42", it) != null }
            .map {
                minOf(
                    400 / (it.width + 2 * RmqrEncoder.QUIET_ZONE),
                    40 / (it.height + 2 * RmqrEncoder.QUIET_ZONE),
                )
            }
        assertEquals(better.max(), scale)
    }

    @Test
    fun `a box too small for any symbol gives nothing`() {
        assertNull(RmqrEncoder.fit("LABEL", boxWidth = 20, boxHeight = 8))
    }
}
